version: '3.8'

services:
  solana-program:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./solana_test_lib/src/dist/program:/usr/src/app/solana_test_lib/src/dist/program
