[package]
name = "solana_test_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
solana-program = "1.17.4"

[lib]
name = "solana_test_lib"
crate-type = ["cdylib", "lib"]
